steps:
# Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/tool-bibimnews/chess-image-from-pgn:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tool-bibimnews/chess-image-from-pgn:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chess-image-from-pgn'
      - '--image'
      - 'gcr.io/tool-bibimnews/chess-image-from-pgn:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
images:
  - gcr.io/tool-bibimnews/chess-image-from-pgn:$COMMIT_SHA

  